### ISSUE TITLE
Error Popup Message in Builder when we click on Update Button 

### ISSUE THREAD

**Issue by Technowlogy-Pushpender** [BlackHacker511/BlackNET#24] opened 2019-12-19 14:42 UTC
Thanks for the latest release v2.0.0.2, Now all things are great, except few ones.

Please Fix these issue to make it more better

* **Screenshot** ~ **Issue 1**

When I click on **Update** button in the Builder, it says **Latest version is installed** and then it shows this message
![Capture](https://user-images.githubusercontent.com/56433698/71180936-330c3480-2299-11ea-8113-4ff86df7a7d4.PNG)

* Issue with `Open Webpage [Visible]` feature ~ **Issue 2**
When I run this feature, nothing happens except giving Message : "Command Has Been Send" in Panel.
Also all the other working features/commands stops working, when i kill the botnet process and then re-run the payload, it starts working again.
But **Open Webpage** command just didn't work. 

* All Stealer Commands are working except one i.e. : **Execute Password Stealer** ~ **Issue 3**

#### Improvements 

**(1)** Add A Feature to Stop Keylogger

**(2.0)** When we Elevate User Status, UAC Popups [**OK Fine**], 
              but it runs the binded/legitemate file also after that.
              This Feature is very suspicious and can't be used in real world,

**(2.1)** Suggest to add this as a tick option, so that we tick the UAC while creating
     payload, and payload then ask for UAC when the user runs it.

**(3)** Add a **Saved Wifi Password Stealer**, I have coded the wifi stealer, and this feauture is pretty simple to implement. Please refer this python codes for help : https://github.com/Technowlogy-Pushpender/creds_harvester/blob/master/get_wifi_pass.py

Waiting for next release!

**Comment by BlackHacker511** [comment] 2019-12-19 15:12
Issue 1: Confirmed => Fixed
Issue 2: To open a webpage you need at least one default browser installed because the feature works fine on my end and I showed it in video the tutorial.
Issue 3: The stealer only steals Chrome saved passwords for now.
if there is no chrome data folder nothing will happen.

**Comment by Technowlogy-Pushpender** [comment] 2019-12-20 05:39
#### Chrome & Firefox Cookies Stealers are working fine,
 **EXCEPT** : **Execute Password Stealer**

![1](https://user-images.githubusercontent.com/56433698/71232457-17943e80-2318-11ea-96d4-ffeff86293b3.PNG)

Both [**Chrome & Firefox**] browsers are installed on my system & also the default browser of windows i.e. **Internet Explorer**

Also suggested to run each command on different thread in payload, as still blocking the other commands when i run the **Open Webpage Feature/command**,

When I run this command, all other commands stop working, till I re-run the payload.

**Comment by BlackHacker511** [comment] 2019-12-20 09:10
DO YOU HAVE SAVED PASSWORDS IN CHROME

**Comment by BlackHacker511** [comment] 2019-12-20 10:54
check the new code is should be fixed 
Threaded the PasswordStealer Function
Threaded OpenWebPage Visible Function
if the Plugin returned false then nothing will happen and the payload will continue to work without issues
if the OpenWeb catch is any error then the payload will continue to work without no issues

enjoy

**Closed** 2019-12-20 12:31 UTC
Labels: bug, confirmed, fixed, v2.0

**Comment by Technowlogy-Pushpender** [comment] 2019-12-20 15:17
> 
> 
> Do you have any saved passwords in chrome?

Now the PasswordStealer Function starts working, Initially I didn't saved the password in chrome

But the **Open Webpage** function has still some bugs.

But now the latest v2.0.0.4 version is not blocking the payload and now I am able to run the commands after running the **Open Webpage** command

I tested twice and even re-install the server in 000webhost and tried to type the website name is different ways like : **https://www.google.com** , **www.google.com**, **google.com**
But nothing works for me

* Also I think a New Issue in **Elevate UAC** tick option:
Payload Successfully Compiles when I tick the UAC option, & when i test it, it ask for UAC 
but all commands are not working [even: **Show msgbox** command not working]

I tried to debug the issue, when i run the command, I opened the Task Manager &
I noticed that a new "Windows Update Manager" process of botnet is created for almost 1 second and then it quite.

This happens every almost 20 seconds.

Also a miner issue:  ~ spelling mistake
![Capture](https://user-images.githubusercontent.com/56433698/71263506-0410c400-2368-11ea-957b-93562fc05fe5.PNG)

Thanks for hard work, keep going :+1:

**Comment by BlackHacker511** [comment] 2019-12-20 17:15
I will look into the elevate user function because it's an highly experimental i never tried it like this using a checkbox

**Comment by BlackHacker511** [comment] 2019-12-20 18:36
the issue is a just a loop I did not check for admin permissions so when the payload starts as admin it will just keep looping in an endless loop close=>restart=>close=>restart fixed now i will just fix stuff then i will push v2.0rc5

**Comment by BlackHacker511** [comment] 2019-12-20 19:09
Fixed 

> 
> 
> > Do you have any saved passwords in chrome?
> 
> Now the PasswordStealer Function starts working, Initially I didn't saved the password in chrome
> 
> But the **Open Webpage** function has still some bugs.
> 
> But now the latest v2.0.0.4 version is not blocking the payload and now I am able to run the commands after running the **Open Webpage** command
> 
> I tested twice and even re-install the server in 000webhost and tried to type the website name is different ways like : **https://www.google.com** , **[www.google.com](http://www.google.com)**, **google.com**
> But nothing works for me
> 
>     * Also I think a New Issue in **Elevate UAC** tick option:
>       Payload Successfully Compiles when I tick the UAC option, & when i test it, it ask for UAC
>       but all commands are not working [even: **Show msgbox** command not working]
> 
> 
> I tried to debug the issue, when i run the command, I opened the Task Manager &
> I noticed that a new "Windows Update Manager" process of botnet is created for almost 1 second and then it quite.
> 
> This happens every almost 20 seconds.
> 
> Also a miner issue: ~ spelling mistake
> ![Capture](https://user-images.githubusercontent.com/56433698/71263506-0410c400-2368-11ea-957b-93562fc05fe5.PNG)
> 
> Thanks for hard work, keep going 👍

Fixed it should work now v2.0rc5
OpenWebpage now will try to open in ur browser if it did not work will execute OpenHidden
if u found any issues report them please

thank you.

**Comment by Technowlogy-Pushpender** [comment] 2019-12-21 13:00
![Capture](https://user-images.githubusercontent.com/56433698/71308217-b192de80-241f-11ea-9ac9-b926fa28c27b.PNG)

Latest Release Fixed the UAC Problem but, when I run **Open Webpage [Visible]**, It quit by showing this error.

Tested Many times, but same issue, it kills the BOTNET

**Comment by Technowlogy-Pushpender** [comment] 2019-12-21 13:05
Also which is the Best place in Panel files, so that I just need to link js code in one file and it get applied to all files.

I want to link this js code, which I saved as **remove.js** in server, want to apply this code to all pages/files

```
window.onload = () => {
    let el = document.querySelector('[alt="www.000webhost.com"]').parentNode.parentNode;
    el.parentNode.removeChild(el);
}
```

**Comment by BlackHacker511** [comment] 2019-12-21 14:42
@Technowlogy-Pushpender 
in components/js.php link this js code in it or wrap it inside a script tag because the components/js.php is used globally except login.php you need to put that code in it to because login.php does not have components/js.php included in it

and i will look into the open webpage issue  because i don't what is it it's working perfectly on my end

**Comment by BlackHacker511** [comment] 2019-12-21 17:05
v2.0rc I created a BrowserHanlder Module that will handle the OpenVisable Requests
it will get check you OS then get default browser , validate that browser, then open the URL using that browser

if this does not please check your OS and your system default browser

**Comment by Technowlogy-Pushpender** [comment] 2019-12-22 06:16
Issue still persist, 

OS: windows 8.1 pro [Target Machine]
Default Browser: Chrome

Also these python codes works for me:

```
import webbrowser
url = "google.com"
webbrowser.open(url)
```

So there might not be a issue with my system.
May be it is not compatible with Windows 8.1 Pro

Any way,  thanks for this reply, it works!

> 
> 
> @Technowlogy-Pushpender
> in components/js.php link this js code in it or wrap it inside a script tag because the components/js.php is used globally except login.php you need to put that code in it to because login.php does not have components/js.php included in it
> 
> and i will look into the open webpage issue because i don't know what is it it's working perfectly on my end
